services:
  serviceregistry:
    container_name: serviceregistry
    # environment:
      # REGISTRY_SERVER: http://serviceregistry:8761/eureka
    image: justadvancetechnology/serviceregitsry_p2
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
     x-aws-autoscaling:
       min: 1
       max: 2
       cpu: 75
     resources:
       limits:
         cpus: '0.5'
         memory: 0.4Gb
    ports:
    - target: 80
      x-aws-protocol: http
    #   - 80:80
    # restart: unless-stopped