---
info:
  component: This is document server

spring:
  profiles: default

server:
  port: 80
# info:
#   version: "1.0.0"
#   title: "This is a Combined-API Gateway cum Document Sevrer. Please select the individual apis from Spec dropdown & Click on right of controller to access the api."
#   description: "This is a Combined-API Gateway cum Document Sevrer. Please select the individual apis from Spec dropdown & Click on right of controller to access the api."
  # Whereas the Openapi definition is avaiable at 
  # USER-SERVICES        =>        https://userservice-production-c3f7.up.railway.app/v3/api-docs
  # HOTEL-SERVICE        =>         https://hotelservice-production.up.railway.app/v3/api-docs
  # RATING-SERVICE       =>         https://ratingservice-production.up.railway.app/v3/api-docs 

  #   Individual Services are also present at below location in Swagger 3 format

  # USER-SERVICE          =>        "https://userservice-production-c3f7.up.railway.app/swagger-ui/index.html"
  # HOTEL-SERVICE         =>        "https://hotelservice-production.up.railway.app/swagger-ui/index.html"
  # RATING-SERVICE        =>        "https://ratingservice-production.up.railway.app/swagger-ui/index.html"

  # Source code for the services is avaiable at https://github.com/praveen1664/SpringBootMicroserviceExample.git
# paths:
#   /:
#     description: File upload and download operations
documentation: 
  baseurl: http://localhost
  swagger: 
    services:
      - 
        name: USER-SERVICE
        url: http://users-loadb-6imypxkm4ia7-272893382.us-east-2.elb.amazonaws.com/v3/api-docs?group=USER-SERVICE
        version: 3.0
        title: "This is a Combined-API Gateway cum Document Sevrer. Please select the individual apis from Spec dropdown & Click on right of controller to access the api."
      - 
        name: HOTEL-SERVICE
        summary: "This is a Combined-API Gateway cum Document Sevrer. Please select the individual apis from Spec dropdown & Click on right of controller to access the api."
        url: http://hotel-loadb-k8aiva487gpr-737544558.us-east-2.elb.amazonaws.com/v3/api-docs?group=HOTEL-SERVICE
        version: 3.0
        
      -
        name: RATING-SERVICE
        description: "This is a Combined-API Gateway cum Document Sevrer. Please select the individual apis from Spec dropdown & Click on right of controller to access the api."
        url: http://ratin-loadb-i6an5c4kpdz0-2054147921.us-east-2.elb.amazonaws.com/v3/api-docs?group=RATING-SERVICE
        version: 3.0

    