services:
  configserver:
    container_name: configserver
    environment:
      EUREKA_URL: "http://servi-loadb-glyhhyriqnv7-367730201.us-east-2.elb.amazonaws.com:80/registry-server/eureka"
    image: justadvancetechnology/configserver_p2
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      x-aws-autoscaling:
        min: 1
        max: 2 
        cpu: 75
      resources:
        limits:
          cpus: '0.1'
          memory: 0.1Gb
    ports:
    # - target: 80
    #   x-aws-protocol: http
      - 80:80
    # depends_on:
    #  - serviceregistry
    # restart: unless-stopped