server:
  port: 80

spring:
  application:
    name: USER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  show-sql: true
  datasource:
#    url: jdbc:postgresql://UserDB:5432/User
    url: ${DB_URL:jdbc:postgresql://localhost:5550/User}
    username: User
    password: User
  # config:
  #   import: optional:configserver:http://localhost:8085

RATING-SERVICE: ${RATINGSERVICE_URL:"http://ratin-loadb-i6an5c4kpdz0-2054147921.us-east-2.elb.amazonaws.com/"}
HOTEL-SERVICE: ${HOTELSERVICE_URL:"http://hotel-loadb-k8aiva487gpr-737544558.us-east-2.elb.amazonaws.com"}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    refresh:
      enable: true
    service-url:
      defaultZone:  ${EUREKA_URL:http://localhost:8761/eureka}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      ratingHotelBreaker:
        limitRefreshPeriod: 2s
        limitForPeriod: 2
        timeoutDuration: 0s

  retry:
    instances:
      ratingHotelBreaker:
        maxAttempts: 3
        waitDuration: 2s
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      rateHotelBreakerAllUsers:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


      # defaultZone:  https://serviceregitsry-production.up.railway.app/eureka
#      defaultZone:  ${REGISTRY_SERVER:http://localhost:8761/eureka}











