server:
  port: 8084
  forward-headers-strategy: framework
spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
          uri: ${USER_SERVICE:lb://localhost:8081/}
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}
        - id: HOTEL-SERVICE
#          uri: lb://HOTEL-SERVICE
          uri: ${HOTEL_SERVICE:lb://localhost:8082/}
          predicates:
            - Path=/hotels/**,/staffs
          filters:
            - RewritePath=/hotels/(?<path>.*), /$\{path}
        - id: RATING-SERVICE
#          uri: lb://RATING-SERVICE
          uri: ${RATING_SERVICE:lb://localhost:8083/}
          predicates:
            - Path=/ratings/**
          filters:
            - RewritePath=/ratings/(?<path>.*), /$\{path}
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8085

springdoc:
  swagger-ui:
    path: /

logging:
  level:
    root: INFO

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    refresh:
      enable: true
    service-url:
      defaultZone:  ${EUREKA_URL:http://localhost:8761/eureka}