services:
  documentservice:
    container_name: documentservice
    # environment:
      # eureka.client.serviceUrl.defaultZone: "http://servi-loadb-1m010cvxc8v81-1110713425.us-east-2.elb.amazonaws.com/eureka" 
      # DB_URL: "jdbc:postgresql://HotelDB:5432/Hotel"
    image: justadvancetechnology/documentservice_wh_3
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      # x-aws-autoscaling:
      #   min: 1
      #   max: 2 
      #   cpu: 75
      resources:
        limits:
          cpus: '1'
          memory: 2Gb
    ports:
    - target: 80
      x-aws-protocol: http
      # - 80:80
    restart: unless-stopped
    healthcheck:
      # test: curl --fail http://127.0.0.1:80/ || exit 1
      test: "curl -f http://127.0.0.1:80/actuator/health/ || exit 1"
      interval: "5m"
      timeout: "5s"
      start_period: "10s"
      retries: 3