services:
  apigateway:
    container_name: apigateway
    environment:
      EUREKA_URL: "http://serviceregistry:8761/eureka"
      RATING_SERVICE: "lb://RATING-SERVICE"
      HOTEL_SERVICE: "lb://HOTEL-SERVICE"
      USER_SERVICE: "lb://USER-SERVICE"
    image: justadvancetechnology/apigateway_v4
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      # replicas: 1
      x-aws-autoscaling:
        min: 1
        max: 2 
        cpu: 75
      resources:
        limits:
          cpus: '0.1'
          memory: 0.1Gb

    ports:
      - 80:8084
    # depends_on:
    #  - UserDB
    #  - serviceregistry
    #  - ratingservice
    #  - hotelservice
    #  - userservice
    restart: unless-stopped
